# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 05:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=120)),
                ('type', models.CharField(max_length=30)),
                ('summary', models.TextField()),
                ('content', models.TextField()),
                ('image_url', models.CharField(max_length=100)),
            ],
        ),
    ]
